# Generated by Django 5.0 on 2024-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('review', models.TextField()),
            ],
        ),
    ]
