# Generated by Django 5.0 on 2024-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='rating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]),
        ),
    ]
