# Generated by Django 5.0 on 2024-10-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_catgory',
            new_name='blog_category',
        ),
    ]
