# Generated by Django 5.0 on 2024-10-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_author',
        ),
    ]
