# Generated by Django 5.0 on 2024-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
